### ISSUE TITLE
The website says it's not available, isn't it?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/uptrace-rust#7]
The website says it's not available, isn't it?

https://uptrace.dev/get/opentelemetry-rust.html

Can I use it with uptrace?

**Comment by vmihailenco** [comment]
I still have to write the docs for uptrace.dev, but you can check instructions in the [README](https://github.com/uptrace/uptrace-rust#quickstart). Seems to be working for me.

**Comment by frederikhors** [comment]
Thanks!
